#!/bin/sh
sudo rm -f /usr/portage/packages/dev-python/kcl-0.0.1.tbz2
sudo rm -rf /usr/lib64/python3.4/site-packages/kcl-0.1-py3.4.egg
vim -O "${@}"
git diff
git add "${@}"
echo "enter a commit message:"
read commitmessage
if [[ "${commitmessage}" =~ $'\n' ]] ;
then
    commitmessage="auto-commit"
fi

git commit -m "auto-commit"
git push
sudo emerge --rage-clean kcl
sudo emerge --tree --quiet-build=n --usepkg=n kcl
sudo rm /usr/portage/packages/dev-python/kcl-0.0.1.tbz2 -f
sudo rm -rf build

