#!/bin/sh
sudo rm -f /usr/portage/packages/dev-python/kcl-0.0.1.tbz2
sudo rm -rf /usr/lib64/python3.4/site-packages/kcl-0.1-py3.4.egg
vim -O "${@}"
git add "${@}"
git commit -m "auto-commit"

sudo emerge --unmerge kcl
sudo emerge --tree --quiet-build=n --usepkg=n kcl
sudo rm /usr/portage/packages/dev-python/kcl-0.0.1.tbz2 -f
sudo rm -rf build

